# Generated by Django 6.1 on 2026-08-19 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('session_id', models.CharField(db_index=True, max_length=80)),
                ('element_tag', models.CharField(default='button', max_length=40)),
                ('element_id', models.CharField(blank=True, max_length=120)),
                ('element_text', models.CharField(blank=True, max_length=255)),
                ('element_selector', models.CharField(blank=True, max_length=255)),
                ('x_percent', models.FloatField(default=0.0)),
                ('y_percent', models.FloatField(default=0.0)),
                ('viewport_width', models.IntegerField(default=1920)),
                ('viewport_height', models.IntegerField(default=1080)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'evento de clique',
                'verbose_name_plural': 'eventos de clique',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='analytics_c_path_053ae8_idx'), models.Index(fields=['element_text', 'path'], name='analytics_c_element_645e86_idx')],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('session_id', models.CharField(db_index=True, max_length=80)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(db_index=True, default='desktop', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('screen_resolution', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pageviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'visualização de página',
                'verbose_name_plural': 'visualizações de página',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['path', 'created_at'], name='analytics_p_path_53ae0e_idx'), models.Index(fields=['session_id', 'created_at'], name='analytics_p_session_fd2f03_idx')],
            },
        ),
    ]
