# Generated by Django 6.1 on 2026-08-23 00:00

from django.db import migrations, models


def normalize_click_coordinates(apps, schema_editor):
    ClickEvent = apps.get_model("analytics", "ClickEvent")
    ClickEvent.objects.filter(x_percent__lt=0).update(x_percent=0)
    ClickEvent.objects.filter(x_percent__gt=100).update(x_percent=100)
    ClickEvent.objects.filter(y_percent__lt=0).update(y_percent=0)
    ClickEvent.objects.filter(y_percent__gt=100).update(y_percent=100)
    ClickEvent.objects.filter(viewport_width__lt=1).update(viewport_width=1)
    ClickEvent.objects.filter(viewport_height__lt=1).update(viewport_height=1)


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(normalize_click_coordinates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='clickevent',
            constraint=models.CheckConstraint(condition=models.Q(('x_percent__gte', 0.0), ('x_percent__lte', 100.0)), name='analytics_click_x_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='clickevent',
            constraint=models.CheckConstraint(condition=models.Q(('y_percent__gte', 0.0), ('y_percent__lte', 100.0)), name='analytics_click_y_percent_range'),
        ),
        migrations.AddConstraint(
            model_name='clickevent',
            constraint=models.CheckConstraint(condition=models.Q(('viewport_height__gte', 1), ('viewport_width__gte', 1)), name='analytics_click_viewport_positive'),
        ),
    ]
