# Generated by Django 6.1 on 2026-08-17 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('public_id', models.CharField(db_index=True, max_length=24, unique=True)),
                ('status', models.CharField(choices=[('new', 'Nova'), ('qualified', 'Qualificada'), ('proposal_sent', 'Proposta enviada'), ('negotiating', 'Em negociação'), ('accepted', 'Aceite'), ('lost', 'Perdida'), ('cancelled', 'Cancelada'), ('fulfilled', 'Concluída')], db_index=True, default='new', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(default='site', max_length=40)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('proposal_note', models.TextField(blank=True)),
                ('quoted_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido de cotação',
                'verbose_name_plural': 'pedidos de cotação',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('image', models.URLField(blank=True)),
                ('quantity', models.PositiveIntegerField()),
                ('quoted_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_items', to='catalog.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.quoterequest')),
            ],
            options={
                'verbose_name': 'item de cotação',
                'verbose_name_plural': 'itens de cotação',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('title', models.CharField(max_length=200)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'Por fazer'), ('done', 'Feita'), ('cancelled', 'Cancelada')], default='todo', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quote_tasks', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='quotes.quoterequest')),
            ],
            options={
                'verbose_name': 'tarefa de cotação',
                'verbose_name_plural': 'tarefas de cotação',
                'ordering': ['due_at', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['status', 'created_at'], name='quotes_quot_status_13321e_idx'),
        ),
        migrations.AddIndex(
            model_name='quoterequest',
            index=models.Index(fields=['assigned_to', 'status'], name='quotes_quot_assigne_a6fdbc_idx'),
        ),
    ]
