# Generated by Django 6.1 on 2026-08-18 22:07

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=220, unique=True, validators=[apps.core.validators.validate_slug])),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('image', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=120)),
                ('author_role', models.CharField(blank=True, max_length=120)),
                ('author_image', models.URLField(blank=True)),
                ('read_time', models.CharField(blank=True, max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'blog'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='catalog.category')),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
                'ordering': ['-published_at', '-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_published', 'status'], name='blog_articl_is_publ_4c0aa2_idx')],
            },
        ),
    ]
