# Generated by Django 6.1 on 2026-08-31 00:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlugRedirect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('old_slug', models.CharField(db_index=True, max_length=220)),
                ('new_slug', models.CharField(db_index=True, max_length=220)),
                ('resource_type', models.CharField(choices=[('article', 'article'), ('project', 'project'), ('product', 'product')], max_length=20)),
            ],
            options={
                'verbose_name': 'redirect de slug',
                'verbose_name_plural': 'redirects de slug',
                'indexes': [models.Index(fields=['old_slug', 'resource_type'], name='core_slugre_old_slu_93f60e_idx')],
                'constraints': [models.UniqueConstraint(fields=('old_slug', 'resource_type'), name='uq_slug_redirect_old_type')],
            },
        ),
    ]
