# Generated by Django 6.1 on 2026-08-23 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterBroadcast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Em fila'), ('running', 'Em execução'), ('completed', 'Concluído'), ('failed', 'Falhou')], db_index=True, default='queued', max_length=20)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'envio de newsletter',
                'verbose_name_plural': 'envios de newsletter',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
