# Generated by Django 6.1 on 2026-08-18 22:07

import apps.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=220, unique=True, validators=[apps.core.validators.validate_slug])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('client', models.CharField(blank=True, max_length=160)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('full_description', models.TextField(blank=True)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('results', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='published', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'portfolio'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='catalog.category')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
