# Generated by Django 6.1 on 2026-08-17 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'registo de auditoria',
                'verbose_name_plural': 'registos de auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
