# Generated by Django 6.1 on 2026-08-23 00:00

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def normalize_catalog_integrity(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Product = apps.get_model("catalog", "Product")

    categories = {category.pk: category for category in Category.objects.all().iterator()}
    for category in categories.values():
        if category.parent_id == category.pk:
            Category.objects.filter(pk=category.pk).update(parent_id=None)
            category.parent_id = None
            continue
        visited = {category.pk}
        ancestor_id = category.parent_id
        invalid = False
        while ancestor_id:
            if ancestor_id in visited:
                invalid = True
                break
            visited.add(ancestor_id)
            ancestor = categories.get(ancestor_id)
            if ancestor is None or ancestor.type != category.type:
                invalid = True
                break
            ancestor_id = ancestor.parent_id
        if invalid:
            Category.objects.filter(pk=category.pk).update(parent_id=None)
            category.parent_id = None

    seen = set()
    for product in Product.objects.order_by("created_at", "pk").iterator():
        normalized = (product.sku or "").strip().upper()
        if normalized:
            candidate = normalized
            if candidate.casefold() in seen:
                suffix = str(product.pk).replace("-", "")[:8].upper()
                candidate = f"{normalized[:51]}-{suffix}"
            while candidate.casefold() in seen:
                candidate = f"{candidate[:51]}-{str(product.pk).replace('-', '')[-8:].upper()}"
            normalized = candidate
            seen.add(normalized.casefold())
        updates = {"sku": normalized}
        if product.subcategory_id:
            subcategory = categories.get(product.subcategory_id)
            if subcategory is None or subcategory.parent_id != product.category_id:
                updates["subcategory_id"] = None
        Product.objects.filter(pk=product.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_catalog_completo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(normalize_catalog_integrity, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('parent_id')), _negated=True), name='category_cannot_parent_itself'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('sku'), condition=models.Q(('sku', ''), _negated=True), name='catalog_product_sku_ci_unique'),
        ),
    ]
